# Generated by Django 5.2.4 on 2025-07-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("INIT", "Init"),
                    ("in_progress", "In Progress"),
                    ("CANCEL", "Cancel"),
                ],
                default="INIT",
                max_length=20,
            ),
        ),
    ]
