# Generated by Django 5.2.4 on 2025-07-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="hex_color",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("INIT", "Init"),
                    ("in_progress", "In Progress"),
                    ("CANCLE", "Cancle"),
                ],
                default="INIT",
                max_length=20,
            ),
        ),
    ]
